from datetime import datetime
import logging
import os


def get_user_logger(user_id: str) -> logging.Logger:
    """
    Create a logger that logs to a file based on the user_id.

    Args:
        user_id (str): The identifier for the user.

    Returns:
        logging.Logger: A logger configured to write to a file for the user.
    """
    # Create a directory for logs if it doesn't exist
    log_directory = 'user_logs'
    if not os.path.exists(log_directory):
        os.makedirs(log_directory)

    # Define the log filename based on the user_id
    log_filename = os.path.join(log_directory, f"{user_id}.log")

    # Create or get an existing logger for the user
    logger = logging.getLogger(user_id)

    # Check if handlers already exist to prevent duplicates
    if not logger.hasHandlers():
        handler = logging.FileHandler(log_filename)
        formatter = logging.Formatter('%(asctime)s ; %(levelname)s ; %(message)s')
        handler.setFormatter(formatter)
        logger.setLevel(logging.INFO)
        logger.addHandler(handler)

    return logger


def log_model_output(user_prompt: str, model_output: str, user_id: str, ground_truth: str = None) -> None:
    """
    Log the model output along with the user prompt and optionally the ground truth for comparison.

    Args:
        user_prompt (str): The prompt provided by the user.
        model_output (str): The output generated by the model.
        user_id (str): The identifier for the user.
        ground_truth (str, optional): The correct output for comparison. Defaults to None.
    """
    logger = get_user_logger(user_id)
    logger.info(f"User Prompt: {user_prompt}")
    logger.info(f"Model Output: {model_output}")
    if ground_truth:
        logger.info(f"Ground Truth: {ground_truth}")
    else:
        logger.info("Ground Truth: Not provided")
    logger.info("-----")


def log_user_interaction(user_id: str, interaction: str) -> None:
    """
    Log user interactions with the application.

    Args:
        user_id (str): The identifier for the user.
        interaction (str): Description of the interaction.
    """
    logger = get_user_logger(user_id)
    logger.info(f"Interaction: {interaction}")


def log_feedback(user_id: str, feedback: str) -> None:
    """
    Log user feedback regarding the model's output.

    Args:
        user_id (str): The identifier for the user.
        feedback (str): The feedback provided by the user.
    """
    logger = get_user_logger(user_id)
    logger.info(f"Feedback: {feedback}")


def log_task_duration(user_prompt: str, duration: float, user_id: str) -> None:
    """
    Log the duration of the task.

    Args:
        user_prompt (str): The prompt provided by the user.
        duration (float): The duration of the task in seconds.
        user_id (str): The identifier for the user.
    """
    logger = get_user_logger(user_id)
    logger.info(f"User Prompt: {user_prompt}")
    logger.info(f"Task Duration: {duration} seconds")
    logger.info("-----")


def log_chat_interaction(
    user_id: str,
    interaction_type: str,
    user_prompt: str = None,
    model_output: str = None,
    model_type: str = None,
    duration: float = None
) -> None:
    """
    Log a complete chat interaction with all relevant details.
    """
    logger = get_user_logger(user_id)
    timestamp = datetime.now().isoformat()
    
    log_entry = f"\n=== Interaction at {timestamp} ===\n"
    log_entry += f"Type: {interaction_type}\n"
    
    if user_prompt:
        log_entry += f"User Prompt: {user_prompt}\n"
    if model_type:
        log_entry += f"Model: {model_type}\n"
    if model_output:
        log_entry += f"Model Output: {model_output}\n"
    if duration:
        log_entry += f"Duration: {duration:.2f} seconds\n"
    
    log_entry += "=" * 50
    
    logger.info(log_entry)
